import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { Activity, ArrowLeft, FileText, MessageSquarePlus, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { listReports } from "@/lib/reports.functions";

export const Route = createFileRoute("/reports/")({
  head: () => ({
    meta: [
      { title: "AlphaQuant AI — Saved Reports" },
      { name: "description", content: "All AI-generated equity research reports saved from your AlphaQuant conversations." },
    ],
  }),
  component: ReportsPage,
});

function ReportsPage() {
  const list = useServerFn(listReports);
  const { data: reports, isLoading } = useQuery({
    queryKey: ["reports"],
    queryFn: () => list(),
  });

  return (
    <main className="min-h-screen px-6 py-10 md:px-12">
      <div className="mx-auto max-w-4xl">
        <header className="mb-8 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <Link to="/">
              <Button variant="ghost" size="sm" className="gap-2 text-muted-foreground">
                <ArrowLeft className="h-4 w-4" /> Dashboard
              </Button>
            </Link>
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/15 glow-ring">
              <Activity className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h1 className="font-display text-xl font-semibold">Saved reports</h1>
              <p className="text-xs text-muted-foreground">Generated by the AlphaQuant analyst agent</p>
            </div>
          </div>
          <Link to="/chat">
            <Button size="sm" className="gap-2">
              <MessageSquarePlus className="h-4 w-4" /> New analysis
            </Button>
          </Link>
        </header>

        {isLoading && <p className="text-sm text-muted-foreground">Loading reports…</p>}

        {!isLoading && (reports?.length ?? 0) === 0 && (
          <div className="glass-panel rounded-2xl p-12 text-center">
            <FileText className="mx-auto h-10 w-10 text-muted-foreground/50" />
            <h2 className="mt-4 font-display text-lg font-semibold">No reports yet</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Ask the analyst to produce and save a report from the chat.
            </p>
            <Link to="/chat">
              <Button className="mt-6 gap-2">
                <MessageSquarePlus className="h-4 w-4" /> Start a conversation
              </Button>
            </Link>
          </div>
        )}

        <div className="grid gap-3">
          {(reports ?? []).map((r) => (
            <Link
              key={r.id}
              to="/reports/$id"
              params={{ id: r.id }}
              className="glass-panel group block rounded-xl p-5 transition hover:border-primary/40"
            >
              <div className="flex items-start justify-between gap-4">
                <div className="min-w-0 flex-1">
                  <h3 className="truncate font-display text-base font-semibold group-hover:text-primary">
                    {r.title}
                  </h3>
                  <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                    <span>{new Date(r.created_at).toLocaleString()}</span>
                    {r.tickers.length > 0 && (
                      <>
                        <span>•</span>
                        <span className="font-mono">{r.tickers.join(", ")}</span>
                      </>
                    )}
                  </div>
                </div>
                {r.recommendation && (
                  <span className="flex items-center gap-1 rounded-full bg-primary/15 px-2.5 py-1 text-xs font-medium text-primary">
                    <TrendingUp className="h-3 w-3" /> {r.recommendation}
                  </span>
                )}
              </div>
            </Link>
          ))}
        </div>
      </div>
    </main>
  );
}
